#!/bin/bash

TEST_MODE="play"
TYPE="wav"
FILE="test.$TYPE"
FORMAT="S16_LE"
#CHANNELS=`amixer -c 1 | grep 'Capture channels'|tr '-' '\n'|wc -l`
RECORDING_ARGS="-t $TYPE -v -Dplughw:1,0 $FILE"
COMMON_ARGS="-f U8"

while [ "$1" ]
do
	if [ "$1" == "-x" ]
	then
		amixer -c 1 sset Mic,0 100% cap
		shift
	elif [ "$1" == "-m" ]
	then
		TEST_MODE="$2"
		shift
		shift
	elif [ "$1" == "-d" ]
	then
		RECORDING_ARGS+=" $1 $2"
		shift
		shift
	elif [ "$1" == "-c" ]
	then
		RECORDING_ARGS+=" $1 $2"
		if [ "$2" -gt 1 ]
		then
			COMMON_ARGS="-f S16_LE"
		fi
		shift
		shift
	elif [ "$1" == "-a" ]
	then
		PLAY_ALL=1
		shift
	else
		COMMON_ARGS+=" $1"
		shift
	fi
done

if [ "$TEST_MODE" != "view" ]
then
	# split recording into individual files
	RECORDING_ARGS+=" -I"
fi

rm -f $FILE*

TEMPFILE=`tempfile`

ARECORD_CMD="arecord $RECORDING_ARGS $COMMON_ARGS"
echo $ARECORD_CMD
if ($ARECORD_CMD > $TEMPFILE 2>&1)
then
	cat $TEMPFILE | egrep '(^[PS]| format|  rate|bits)'
	if [ "$TEST_MODE" == "view" ]
	then
		audacity $FILE
	else
		if [ "$PLAY_ALL" ]
		then
			APLAY_CMD="aplay $COMMON_ARGS $FILE.*"
		else
			APLAY_CMD="aplay $COMMON_ARGS $FILE.0"
		fi
		echo $APLAY_CMD
		$APLAY_CMD
	fi
else
	echo "Capture Failed:"
	cat $TEMPFILE
fi
rm -f $TEMPFILE
